import type { KleRaw } from "./types";

/**
 * Windows «Persian (Standard)» / ISIRI 9147 on 60% ANSI geometry.
 * Physical positions match {@link TEMPLATE_60_ANSI_KLE}; labels are shift\\nbase.
 */
export const PERSIAN_STANDARD_60_KLE: KleRaw = [
  [
    "\u200d",
    "!\n۱",
    "٬\n۲",
    "٫\n۳",
    "﷼\n۴",
    "٪\n۵",
    "×\n۶",
    "،\n۷",
    "*\n۸",
    ")\n۹",
    "(\n۰",
    "ـ\n-",
    "+\n=",
    { w: 2 },
    "Backspace",
  ],
  [
    { w: 1.5 },
    "Tab",
    "ْ\nض",
    "ٌ\nص",
    "ٍ\nث",
    "ً\nق",
    "ُ\nف",
    "ِ\nغ",
    "َ\nع",
    "ّ\nه",
    "]\nخ",
    "[\nح",
    "}\nج",
    "{\nچ",
    { w: 1.5 },
    "|\n\\",
  ],
  [
    { w: 1.75 },
    "Caps Lock",
    "ؤ\nش",
    "ئ\nس",
    "ي\nی",
    "إ\nب",
    "أ\nل",
    "آ\nا",
    "ة\nت",
    "»\nن",
    "«\nم",
    ":\nک",
    "؛\nگ",
    { w: 2.25 },
    "Enter",
  ],
  [
    { w: 2.25 },
    "Shift",
    "ك\nظ",
    "ط",
    "ژ\nز",
    "ٰ\nر",
    "\u200c\nذ",
    "ٴ\nد",
    "ء\nپ",
    ">\nو",
    "<\n.",
    "؟\n/",
    { w: 2.75 },
    "Shift",
  ],
  [
    { w: 1.25 },
    "Ctrl",
    { w: 1.25 },
    "Win",
    { w: 1.25 },
    "Alt",
    { a: 7, w: 6.25 },
    "\u200c\n ",
    { a: 4, w: 1.25 },
    "Alt",
    { w: 1.25 },
    "Win",
    { w: 1.25 },
    "Menu",
    { w: 1.25 },
    "Ctrl",
  ],
];

export const PERSIAN_STANDARD_60_ID = "persian-standard-60" as const;

export const PERSIAN_STANDARD_60_NAME = "Persian Standard" as const;